name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: [8.4, 8.3, 8.2, 8.1, 8.0]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install composer dependencies
        run: |
          composer update --prefer-dist --no-interaction --optimize-autoloader

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
